# Generated by Django 3.2.20 on 2024-11-01 00:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import user.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_price'),
        ('order', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Сформирован'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=user.catalog.models.Decimal128Field(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', user.catalog.models.Decimal128Field(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
