# Generated by Django 3.2.20 on 2024-11-01 00:12

from decimal import Decimal
from django.db import migrations
import user.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20241101_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=user.catalog.models.Decimal128Field(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
