# Generated by Django 3.2.20 on 2024-10-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_product_userproductinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductinteraction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userproductinteraction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='UserProductInteraction',
        ),
    ]
